# Generated by Django 4.2.5 on 2023-11-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_game', '0002_memorygame_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorygame',
            name='user',
        ),
        migrations.AddField(
            model_name='memorygame',
            name='user_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
