# Generated by Django 4.2.5 on 2023-12-18 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memory_game', '0003_remove_memorygame_user_memorygame_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorygame',
            name='user_id',
        ),
        migrations.AddField(
            model_name='memorygame',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
