# Generated by Django 4.2.5 on 2024-01-09 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memory_game', '0004_remove_memorygame_user_id_memorygame_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startLives', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='memorygame',
            name='settings',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='memory_game.gamesettings'),
            preserve_default=False,
        ),
    ]
