# Generated by Django 4.2.5 on 2024-01-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_game', '0005_gamesettings_memorygame_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesettings',
            old_name='startLives',
            new_name='lives',
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='mistakes',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='startLevel',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
