# Generated by Django 4.2.5 on 2024-01-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_game', '0006_rename_startlives_gamesettings_lives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='title',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
