# Generated by Django 4.2.5 on 2024-01-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_game', '0007_gamesettings_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='startTime',
            field=models.FloatField(default=2.0),
        ),
    ]
