# Generated by Django 4.2.5 on 2024-01-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_game', '0008_gamesettings_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='timeIncrease',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='lives',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='mistakes',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='startLevel',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='startTime',
            field=models.IntegerField(default=3000),
        ),
    ]
