# Generated by Django 4.2.5 on 2024-02-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memory_game', '0011_memorygame_customgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorygame',
            name='settings',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='memory_game.gamesettings'),
        ),
    ]
