# Generated by Django 4.2.5 on 2024-02-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_game', '0016_alter_memorygame_gamedate_alter_memorygame_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorygame',
            name='gameDate',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
